# Generated by Django 4.2.16 on 2025-03-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 17, 16, 48, 15, 164886)
            ),
        ),
    ]
